development:
  adapter: postgresql
  encoding: unicode
  database: myapp_dev1
  pool: 5
  username: lahrei
  password: 5656

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test1
  pool: 5
  username: lahrei
  password: 5656